# Generated by Django 3.2.5 on 2021-10-07 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runID', models.PositiveIntegerField(unique=True)),
                ('method', models.CharField(max_length=100)),
                ('productLength', models.PositiveIntegerField(default=1500, verbose_name='Product length (bp)')),
                ('primerMonovalentCations', models.FloatField(default=50, verbose_name='Monovalent cations (mM)')),
                ('primerDivalentCations', models.FloatField(default=1.5, verbose_name='Divalent cations (mM)')),
                ('primerDNTPs', models.FloatField(default=1.75, verbose_name='dNTPs (mM)')),
                ('primerConcentration', models.FloatField(default=300, verbose_name='Annealing oligo concentration (nM)')),
                ('primerAnnealingTemp', models.FloatField(default=55, verbose_name='Primer annealing temperature (°C)')),
                ('probeMonovalentCations', models.FloatField(default=25, verbose_name='Monovalent cations (mM)')),
                ('probeDivalentCations', models.FloatField(default=10, verbose_name='Divalent cations (mM)')),
                ('probeDNTPs', models.FloatField(default=0, verbose_name='dNTPs (mM)')),
                ('probeConcentration', models.FloatField(default=50, verbose_name='Probe concentration (nM)')),
                ('probeAnnealingTemp', models.FloatField(default=70, verbose_name='Probe annealing temperature (°C)')),
                ('primerMismatchesTotal', models.PositiveSmallIntegerField(default=0, verbose_name='Primer mismatches')),
                ('probeMismatchesTotal', models.PositiveSmallIntegerField(default=0, verbose_name='Probe mismatches')),
                ('dbs', models.CharField(blank=True, max_length=10000, null=True)),
                ('crossCheck', models.BooleanField(default=False, verbose_name='Cross-check primer packages')),
                ('dimerCheck', models.BooleanField(default=False, verbose_name='Secondary structure check')),
                ('checkProbesOnly', models.BooleanField(default=False, verbose_name='Check probes only')),
                ('downloaded', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('arvi', models.BooleanField(blank=True, default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Notification email')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jsonMaps', models.TextField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='', max_length=40)),
                ('substep', models.CharField(default='', max_length=40)),
                ('finished', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('error_log', models.CharField(blank=True, default='', max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='submission.run')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=255)),
                ('contig', models.TextField()),
                ('primer1', models.CharField(max_length=255)),
                ('primer2', models.CharField(max_length=255)),
                ('probe', models.CharField(max_length=255)),
                ('primer1Package', models.CharField(max_length=255)),
                ('primer2Package', models.CharField(max_length=255)),
                ('probePackage', models.CharField(max_length=255)),
                ('startPos1', models.PositiveIntegerField()),
                ('endPos1', models.PositiveIntegerField()),
                ('startPos2', models.PositiveIntegerField()),
                ('endPos2', models.PositiveIntegerField()),
                ('startPos3', models.PositiveIntegerField()),
                ('endPos3', models.PositiveIntegerField()),
                ('productSize', models.PositiveIntegerField()),
                ('noMismatchesLeft', models.CharField(max_length=5)),
                ('noMismatchesRight', models.CharField(max_length=5)),
                ('noMismatchesProbe', models.CharField(max_length=5)),
                ('mismatchesLeft', models.CharField(max_length=255)),
                ('mismatchesRight', models.CharField(max_length=255)),
                ('mismatchesProbe', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=1000)),
                ('product', models.TextField()),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='submission.run')),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.FileField(upload_to='')),
                ('results_all', models.FileField(upload_to='')),
                ('results_wob', models.FileField(upload_to='')),
                ('results_dimer', models.FileField(blank=True, null=True, upload_to='')),
                ('isAvailable', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submission.run')),
            ],
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('orig_filename', models.CharField(max_length=255)),
                ('seqtype', models.CharField(max_length=64)),
                ('filetype', models.CharField(max_length=64)),
                ('isAvailable', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tmpRunID', models.PositiveIntegerField()),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submission.run')),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=255)),
                ('contig', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('startPos', models.PositiveIntegerField()),
                ('endPos', models.PositiveIntegerField()),
                ('mismatchesTotal', models.CharField(max_length=5)),
                ('strand', models.PositiveSmallIntegerField()),
                ('hitSequence', models.TextField()),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hit', to='submission.run')),
            ],
        ),
    ]
